name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Add i386 architecture
      run: dpkg --add-architecture i386
      
    - name: Update repository
      run: apt-get update

    - name: Install build dependencies
      run: apt-get install -qq -y wget unzip build-essential gcc-12-multilib g++-12-multilib libgcc1:i386
    
    - name: Update alternatives
      run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12

    - name: Run build
      working-directory: ./MatchBot
      run: make
    
    - name: Move release file to publish
      run: |
        # Make Match BOT path
        mkdir -p publish/addons/matchbot/dlls

        # Move released file to dlls
        mv ./MatchBot/Release/matchbot_mm.so publish/addons/matchbot/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Download metamod-r
      run: |
        # Get latest release version of metamod-r
        wget --quiet https://github.com/theAsmodai/metamod-r/releases/download/1.3.0.131/metamod-bin-1.3.0.131.zip

        # Unzip metamod library to metamod folder
        unzip -p metamod-bin*.zip addons/metamod/metamod_i386.so > publish/addons/metamod/metamod_i386.so

    - name: Download hitbox_fixer
      run: |
        # Get latest release version of hitbox_fixer
        wget --quiet https://github.com/Garey27/hitbox_fixer/releases/download/1.1.4/hitbox_fix-bin-1.1.4.zip

        # Unzip hitbox_fixer library to metamod folder
        unzip -p hitbox_fix-bin*.zip addons/hitbox_fix/hitbox_fix_mm_i386.so > publish/addons/hitbox_fix/hitbox_fix_mm_i386.so

    - name: Download accuracy-fix
      run: |
        # Get latest release version of accuracy-fix
        wget --quiet https://github.com/SmileYzn/AccuracyFix/releases/download/1.0.2/accuracyfix-linux.zip

        # Unzip accuracy-fix library to metamod folder
        unzip -p accuracyfix-linux.zip addons/accuracyfix/dlls/accuracyfix_mm.so > publish/addons/accuracyfix/accuracyfix_mm.so

    - name: Deploy artifacts
      uses: actions/upload-artifact@v4
      with:
        name: matchbot-linux
        path: publish/*
